### ISSUE TITLE
Непонятный алерт

### ISSUE THREAD

**Issue by skywinder** [BANKEX/hackathon-ctf#2]
![image](https://user-images.githubusercontent.com/3356474/40268463-363ef1b0-5b76-11e8-969e-a925c61f6eb1.png)
напишите про метамаск. Мало кто знает про web3 provider.

**Comment by skywinder** [comment]
https://github.com/BANKEX/proof-of-skill-hackathon-ctf/blob/7b78585e306fc5474abff8328b0528ba728c1479/docs/assets/js/connection.js#L6

**Comment by antonpegov** [comment]
Fixed with commit 620af4af5962f4da972536b4d79e314109457f46
