### ISSUE TITLE
Не смог зарегистрироваться - выдало ошибкуout of gas

### ISSUE THREAD

**Issue by skywinder** [BANKEX/hackathon-ctf#3]
<img width="1552" alt="screen shot 2018-05-19 at 15 14 31" src="https://user-images.githubusercontent.com/3356474/40268514-759ddcd0-5b77-11e8-8d76-4166d39b4cb4.png">

**Comment by shamatar** [comment]
Руками в мерамаске попробуй поставить побольше, 100к

**Comment by antonpegov** [comment]
Невозможно повторить, был локальный баг Метамаска.
